name: open_app_settings
description: A remaster plugin of app_settings. app_setting use Kotlin and Swift may cause build issue, so this plugin used Java and ObjC.
version: 2.0.1
homepage: https://github.com/mjl0602/open_app_settings
repository: https://github.com/mjl0602/open_app_settings
publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.oversketch.open_app_settings
        pluginClass: OpenAppSettingsPlugin
      ios:
        pluginClass: OpenAppSettingsPlugin

